name: MetaCall Examples CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  Linux:
    name: Linux - Ubuntu Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install MetaCall
        run: |
          sudo apt update
          curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

      - name: Verify MetaCall installation
        run: | 
          metacall
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Tests Suits
        run: |
          find test-suites -type f -name "*.yaml" -exec python ./testing.py -f {} -V \;

  Windows:
    name: Windows Run
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Install MetaCall
        shell: powershell
        run: |
          powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/metacall/install/master/install.ps1')))"
            
      - name: Add MetaCall to PATH
        run: | 
          echo C:\Users\runneradmin\AppData\Local\MetaCall >> $env:GITHUB_PATH
        shell: powershell
        
      - name: Verify MetaCall installation
        shell: powershell
        run: | 
          metacall

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Test Suits
        shell: bash
        run: |
          find test-suites -type f -name "*.yaml" -exec python ./testing.py -f {} -V \;
    

  # MacOS:
  #   name: MacOS Run
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'
      
  #     - name: Install MetaCall
  #       run: |
  #         curl --insecure -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh -s -- --no-check-certificate --no-docker-fallback

  #     - name: Install Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
          
  #     - name: Run Tests Suits
  #       run: |
  #         find test-suites -type f -name "*.yaml" -exec python ./testing.py -f {} -V \;
